# Generated by Django 5.2.10 on 2026-01-28 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='target_sessions',
            field=models.PositiveIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='workout',
            name='target_attempts',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
