# Generated by Django 5.2.10 on 2026-01-28 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0002_workout_target_sessions_and_more'),
    ]

    operations = []
