# Generated by Django 5.2.10 on 2026-03-27 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0004_user_coachprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="workout",
            name="assigned_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_workouts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
