# Generated by Django 5.2.10 on 2026-03-28 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0005_workout_assigned_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="playerprofile",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
