# Generated by Django 5.2.10 on 2026-03-28 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0006_profile_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerprofile',
            name='date_of_birth',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AlterField(
            model_name='playerprofile',
            name='height_cm',
            field=models.PositiveIntegerField(default=180),
        ),
    ]
