# Generated by Django 5.2.10 on 2026-03-28 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("workouts", "0007_connectionrequest"),
        ("workouts", "0007_alter_playerprofile_date_of_birth_and_more"),
    ]

    operations = []
