# Generated by Django 5.2.10 on 2026-04-15 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0008_merge_0007_connectionrequest_0007_alter_playerprofile_date_of_birth_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_attempts', models.PositiveIntegerField(default=10)),
                ('target_sessions', models.PositiveIntegerField(default=3)),
                ('goal_percentage', models.FloatField(default=75.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workout_templates', to='workouts.coachprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
