# Generated by Django 5.2.10 on 2026-04-17 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0009_workouttemplate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('WORKOUT_ASSIGNED', 'Workout Assigned'), ('CONNECTION_ACCEPTED', 'Connection Accepted'), ('CONNECTION_REQUESTED', 'Connection Requested'), ('WORKOUT_COMPLETED', 'Workout Completed'), ('SESSION_ADDED', 'Session Added')], max_length=30)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('related_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications_initiated_by', to=settings.AUTH_USER_MODEL)),
                ('related_workout', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='workouts.workout')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='workouts_no_user_id_3657bd_idx'), models.Index(fields=['user', 'is_read'], name='workouts_no_user_id_2a344b_idx')],
            },
        ),
    ]
