# Generated by Django 5.2.10 on 2026-06-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0011_devicepushtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='profile_photo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='profile_photo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
