# Generated by Django 5.2.10 on 2026-06-04 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0012_coachprofile_profile_photo_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coachprofile',
            name='profile_photo_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='playerprofile',
            name='profile_photo_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
